sudo: required
services:
  - docker
before_install:
  - docker build -t nbhaohao/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e "CI=true" nbhaohao/react-test npm run test
after_success:
  - docker build -t nbhaohao/multi-client ./client
  - docker build -t nbhaohao/multi-nginx ./nginx
  - docker build -t nbhaohao/multi-server ./server
  - docker build -t nbhaohao/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nbhaohao/multi-client
  - docker push nbhaohao/multi-nginx
  - docker push nbhaohao/multi-server
  - docker push nbhaohao/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multiple-docker'
  env: 'Multipledocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-609035547674'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY